<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXLgyLmY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXLgyLmY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXLgyLmY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXLgyLmY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXLgyLmY\App_KernelDevDebugContainer([
    'container.build_hash' => 'XLgyLmY',
    'container.build_id' => '65a37170',
    'container.build_time' => 1606730447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXLgyLmY');
