<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\BlogController::showPosts'], [], [['text', '/blog']], [], []],
    'postblog' => [[], ['_controller' => 'App\\Controller\\BlogController::addPost'], [], [['text', '/newPost']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], []],
    'start_login' => [[], ['_controller' => 'App\\Controller\\LoginController::startLogin'], [], [['text', '/startLogin']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], []],
];
